### ISSUE TITLE
Setting for unauthenticated /metrics when using authentication for the Web UI

### ISSUE THREAD

**Issue by fred-vogt-dod** [mher/flower#1066]
**Is your feature request related to a problem? Please describe.**
Option to have `/healthcheck` and `/metrics` remain `unauthenticated` when using authentication for the web UI.

**Describe the solution you'd like**
Similar to `/healthcheck` being unauthenticated, perhaps the prometheus metrics should also be unauthenticated by default.

Removing the tornado decorator `@ tornado.web.authenticated` from `flower.views.monitor.Metrics.get()` still results in 401 from `flower.views.BaseHandler. get_current_user()`.

**Comment by ChakshuGautam** [comment]
@fred-vogt-dod  I am using the `basic_auth` feature in Prometheus config. Is that a bad design pattern?

**Comment by kodless** [comment]
**LEEK: a new celery tasks monitoring tool!**

Repository: https://github.com/kodless/leek

Website: https://tryleek.com/

**Comment by mher** [comment]
@Tomasz-Kluczkowski what do you think about this enhancement request?

**Comment by Tomasz-Kluczkowski** [comment]
> @Tomasz-Kluczkowski what do you think about this enhancement request?

I think I could look into it :). I have not yet played with authentication of Flower (not the use case we have at work) but I can see how it is done and explore the options.

@fred-vogt-dod / @mher , could you answer a few questions please:
- What kind of authentication are you using when connecting to Flower please?
- are we thinking of this new behaviour for all kinds of authentication? I assume we have basic user/password and SSL based?
- I assume we would like a command line argument that disables authentication of metrics endpoint but by default it is not exposed?
- also what is the rationale behind making it unauthenticated? (just for me to understand)

MVP (to be confirmed):
- add boolean command line flag to disable auth of metrics endpoint
- make sure code for metrics endpoint respects that

**Comment by mher** [comment]
@fred-vogt-dod is suggesting to remove authentication from `/metrics` endpoint

**Comment by Tomasz-Kluczkowski** [comment]
Ok, so we do not want to have it authenticated always? 
All I want to know if we see the need to have it authenticated in some circumstances and want a flag for it?
Obviously no flag is easier :).

**Comment by Tomasz-Kluczkowski** [comment]
> @fred-vogt-dod is suggesting to remove authentication from `/metrics` endpoint

Sure, but do we want to make it unauthenticated always or just by default and have a flag that enables authentication again?

**Comment by Tomasz-Kluczkowski** [comment]
@mher Please assign me to this one. I will ponder about it (although going on hols so it will take a while).

**Comment by Tomasz-Kluczkowski** [comment]
@mher is this only for basic_auth and metrics?

Also the decorator: `@web.authenticated`, is it applicable to other than basic auth forms of authentication? I can see why removing it does not work for basic auth and metrics is still authenticated but was wondering if it works for others...

**Comment by Tomasz-Kluczkowski** [comment]
@mher 
I am back to this one.

Since we treat different forms of authentication differently (basic and Oauth2 is in `get_current_user` in `BaseHandler`, but others have their own login handlers) I want to have an option to disable auth that works for all of them.
Thankfully `get_current_user`  in `BaseHandler` is called first and we can disable authentication there.

Therefore, my design currently is:
- have a list of auth exempt endpoints, by default: ['/healthcheck', '/metrics'], probably in auth.py?
- you can override this list via command line arg/env var, if all must be authenticated: --auth_exempt_endpoints=[]
- `BaseHandler` has a method `is_auth_exempt` (name is work in progress) which checks what URI the `RequestHandler` tornado object (which `BaseHandler` inherits from) points currently at and if in exempt - avoid authentication. I think just returning `True` should work. 
- I am not happy with returning a boolean from user getting method so maybe introduce something else for this purpose - some constant like USER_EXEMPT_FROM_AUTH = 'user_exempt_from_auth' (we can also use it on line 80 to avoid returning True as a user) or ENDPOINT_EXEMPT_FROM_AUTH to suggest better what it is.
- `is_auth_exempt` method is the first check in `get_current_user` of the `BaseHandler`, if exempt just return whatever is needed to avoid login routine and access denied error as in the point above.
- all other `LoginHandlers` first go through `BaseHandler` and its `get_current_user` so should skip auth anyway.

Does that design sound sensible?

**Comment by mher** [comment]
I'd suggest to make things simple and remove authentication for `/metrics`. Just deleting https://github.com/mher/flower/blob/master/flower/views/monitor.py#L10 will solve the issue.

**Comment by fred-vogt-dod** [comment]
@Tomasz-Kluczkowski - thanks for implementing this

**Comment by hadpro24** [comment]
Hello guys how are fix that ? I use docker image. Can you help me
