### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by dpolonsky** [mher/flower#117]
It would be great if you could add user authentication and 2 types of user: admin who can cancel consumers and viewer for read only mode.
thx
D

**Comment by leonardbinet** [comment]
Is it a considered enhancement? It would be great to have a read-only mode.

**Comment by jheld** [comment]
I'm looking to implement this and would be happy to share in a PR.

**Comment by rns4731** [comment]
+1 very interested in this feature.

**Comment by jheld** [comment]
So, my thinking is assuming we leverage the existing Oauth2 code, then we could go one of 2 (or more?) ways:

- Does the Identity provider (Oauth2/google/etc) provide information about the user which would help define these roles naturally? E.g. would the Oauth2 give us user information that says they're an admin?
- If the Identity provider does _not_ have this information, then Flower will need a way to store this information and let an admin user manage/configure it in hopefully easy (but secure) ways.

Let's assume the worst. If Flower must manage this information on behalf of the admin user, then how will it be stored? Is there some CSV/JSON file that they dump into flower via browser/API? Or Flower is configured to load from remote storage (e.g. AWS' S3).

Going simpler than S3 it could be a shelve file or SQLite. Both are easy to manage from python. But if flower is going to store that information locally, it will need password protection of some sort. Maybe SQLite provides that? I don't know.

Again, the authentication aspect is basically already covered because Flower handles this. It's the authorization/permission issue we're looking to solve.

**Comment by mher** [comment]
There are no plans to work on this feature at the moment until someone decides to contribute to the project.
