### ISSUE TITLE
Want to know from where Tasks are listing in "Task" tab

### ISSUE THREAD

**Issue by MuhammadTalha10** [mher/flower#1226]
Want to know from where Tasks and listing in "Task" tab ?
is this from celery_result_backend ? or from any where else because whenever i restart flower locally it removes the task list in "Task" tables

**Comment by frontierpsycho** [comment]
I'm not the maintainer for this project, but I think I can answer the question, since I was just looking into it. Flower listens on events from your celery cluster, and stores the relevant data in memory. That's why restarting removes all tasks.

You can enable the `persistent` flag, which makes Flower persist the data from memory into disk, and read them back on startup. This doesn't seem to restore everything perfectly, but you at least get the successful tasks on the list after startup.
