### ISSUE TITLE
Flower doesn't display custom task states

### ISSUE THREAD

**Issue by mmoya** [mher/flower#143]
Hello

    @task
    def fancy_task():
        fancy_task.update_state(state='CUSTOM_STATE1')
        time.sleep(30)

when I call the above task, flower displays `STARTED` and then `SUCCESS`, `CUSTOM_STATE1` is never shown while the task is waiting. Note that `AsyncResult(task_id).state` works as expected.

**Comment by daniel-cohen** [comment]
I can see send_event was added to the celery API, I just don't see any of these events appear in flower. Has this been implemented ?

**Comment by AndreLobato** [comment]
Just an addendum, I did manage to use custom tasks events on flower, indeed I used send_event to communicate the state updates on my task. To be able to use the web-socket I had to add the event type to the EVENTS list at api/events.py and to the urls.py the respective path. I my case was created the task-running event so I could have progress bar updates for long running tasks. Worked fine. Thanks

**Comment by daniel-cohen** [comment]
@AndreLobato Maybe you should make it a pull request and convince whoever's in charge to accept it.
Having a progress bar for long running tasks will be great and pretty much what I'm trying to do as well.

I am sure lots of people would appreciate it.
Maybe we can find a way to make it more generic though. Maybe add events to listen to based on configuration instead of code ?

**Comment by AndreLobato** [comment]
@daniel-cohen  The progress state I did was inspired by the jobtastic module, I first implemented using jobstatic, but this module still requires celery 3.0 and depends on a django-celery result database scheme to store the progress data, which I tought was unecessary in my case since I was not using django. Also would require to use a database such as postgres and it's not so good for high availability. With the celery send-event task method is very trivial to add another state such as progress. Just as Ask mentioned above. A few more tweeks was needed on the templates so could parse the result when there is progress information or not. I may try to work in a clean way to be easy to implement the progress bar just for flower, that way any celery task that uses the send_event with the task-running or task-progress would reflect in a progress bar by flower on the result field while tasks run (not sure if would be accepted). I am also working on having the "Tasks" section of flower been updated by web sockets, so that could be used to real-time monitoring as well, with progress bar and sorteable columns as well, would be cool, but that would be another pull request.

**Comment by mher** [comment]
#478 is merged

**Comment by adampl** [comment]
Note that every Task instance has a `send_event` method which can be called instead of the dispatcher method as suggested above. This is much more elegant.

**Comment by bahmandad** [comment]
s
