### ISSUE TITLE
Revoke option in celery flower not revoking the task 

### ISSUE THREAD

**Issue by Prathika** [mher/flower#169]
Have tried the below methods. I guess the revoke signal is not been received by the worker, a couple of tasks alone got ignored on the worker terminal, I was able to see the message "IGNORING TASK:xxxx" message am not able to figure out when this revoke actually worked.

task_id='xxxxxxx'

from celery.task.control import revoke
revoke(task_id, terminate=True)

from celery.app.control import Control
celery_control = Control()
celery_control.revoke(task_id)

**Comment by pj** [comment]
I think I might have come across a similar problem with flower not terminating a process.  The cause was that I was running on Windows 7 using --pool=solo, because celery wasn't sending results back properly when running with the default prefork pool. To fix this I found I had to specify the backend using update config rather than the constructor:

    app.conf.update(
        CELERY_RESULT_BACKEND='redis://localhost:6379/0'
    )

Rather than:

     Celery('tasks', broker='redis://localhost//', backend='redis://localhost:6379/0')

As described here: https://github.com/celery/celery/issues/897.
