### ISSUE TITLE
send email alarm when worker off-line or queue length is too long?

### ISSUE THREAD

**Issue by max8899** [mher/flower#566]
Hi,

I've use flower for some time, may be more than one year.

Flower is a great tool for monitoring my celery cluster, but I found it just monitor the status and show data on web, there is no place to config an email settings or sms to send it to admins?

And flower does not support save the task result to a real db,  while someone will need the history data to find out what happens

Need some advise on my problem, thanks.

**Comment by max8899** [comment]
@ask @mher ?

**Comment by cralston0** [comment]
I'm just a user, so don't take this as anything official, but that's not really the kind of monitoring Flower does.

Because of all the different brokers that Celery can use, and the usage patterns that can exist for any environment, it would be hard to reliably get useful information for this based on how Flower is querying the Celery workers.  There are dozens of off-the-shelf tools for monitoring your broker directly and generate alerts based on that -- Nagios, Munin, etc for running your own service and subscription cloud-based services like Datadog and New Relic.

These all do a much better job than trying to get Flower to reinvent the wheel and add a huge feature outside of its scope.

**Comment by mher** [comment]
For full task history, it is better to use a celery result backend

**Comment by mher** [comment]
Flower currently doesn't support any alerting
