### ISSUE TITLE
Invalid URL used for datatable query

### ISSUE THREAD

**Issue by erdnaxeli** [mher/flower#618]
Hi,

When using flower with --url_prefix, I can't list tasks (tasks tab). I see queries to `https://<url_prefix>/tasks/datatable?…`, the domain is missing. With the correct URL, the query works fine, I can get the JSON.

Using flower 0.9.1.

**Comment by insanemainframe** [comment]
Hi, i have same problem
flower==0.9.1

**Comment by xavierhardy** [comment]
Here too

**Comment by xavierhardy** [comment]
I think I found the error in `flower/static/js/flower.js` in `url_prefix()`, line 32:
https://github.com/mher/flower/blob/master/flower/static/js/flower.js#L32
```js
function url_prefix() {
    var url_prefix = $('#url_prefix').val();
    if (url_prefix) {
        return '/' + url_prefix;
    }
    return '';
}
```
`/` is prepended to the `url_prefix` but it does not whether `url_prefix` starts with a `/` or not, resulting in `//your/custom/url/path` instead of `/your/custom/url/path`.

In order to fix your problem, you must simply remove any `/` at the beginning of the `url_prefix` argument.
