### ISSUE TITLE
Question: flower behind load balancer not updating status

### ISSUE THREAD

**Issue by adamtay82** [mher/flower#699]
More a question than an issue, I think .... but running in to something that I think needs a flower expert (flower 0.9.1):

- I have Flower running on an ECS cluster / container, so ideally I need a load balancer to point to it so I have a constant URL
- when I access Flower directly via the IP all works fine e.g., http://xx.xx.xx.xx:5555/
- when I access Flower through the load balancer the "status" column will not update - all workers read as online e.g., http://myloadbalancer:5555/

I believe all traffic should be coming through (including ICMP) and I'm forwarding ports 5555,80 etc., but I'm sure I'm missing something.

I guess it boils down to what protocols and ports Flower needs to be able to update that status column.  Can anyone help?

**Comment by adamtay82** [comment]
Ah - I believe this might be because WebSockets are not supported by AWS's classic load balancer.  Would that cause Flower to break?

**Comment by mher** [comment]
Please try the master version. WebSockets are removed from the master version. I'm going to release a new version which doesn't rely on WebSockets.

**Comment by briancaffey** [comment]
@adamtay82 @mher I have a related question about running ECS behind an AWS load balancer (ALB). I think my flower container if failing health checks because I'm using `--basic_auth` to secure flower. Are you using authentication? Is there a workaround for this issue? I am able to get flower working just fine without `--basic_auth`, but I can't make it work when I set this option.
