### ISSUE TITLE
flower on Docker

### ISSUE THREAD

**Issue by viiicky** [mher/flower#844]
The documentation [here](https://github.com/mher/flower/blob/master/docs/docker.rst#docker-usage) says:

> Now, clone this repository...

And the dockerfile has this line [here](https://github.com/mher/flower/blob/2f674aa4ed4f11243822869b70027c0b6f07a61c/Dockerfile#L7):
`RUN pip install redis flower`

I am not sure why do we need to clone the repo for this. We are anyway pip installing Flower, then whats the point of cloning the whole repo. Can't I just take the Dockerfile and get away with this? Am I missing something obvious?

**Comment by bstiel** [comment]
I think it's because the repository contains the Dockerfile (unlike the pip package). So you can clone the repo and build the image with "docker".
The "pip install flower" is the bit that shouldn't be in there as we have the source code and should "build" flower in the Dockerfile. But I guess it's for keeping the consistency between the pip and docker image versions?
Having said that, I usually just use the mher/flower image from Dockerhub.
