### ISSUE TITLE
Refresh workers button not accessible

### ISSUE THREAD

**Issue by thenewguy** [mher/flower#856]
I am observing "unknown worker" error when trying to view individual workers.  The worker list page works, but does not offer a refresh button.  If I pass ?refresh=True via the url, the page is reloaded and the links worked again.

This issue is related https://github.com/mher/flower/issues/546

**Comment by CalebFenton** [comment]
Confirmed this bug is still happening with flower 0.9.3, celery 4.3.0, and using SSL for broker and result backend (not sure if that matters)

I couldn't get details on any of my workers -- they all said "unknown worker". The `?refresh=True` work-around fixed the problem, but it'd be nice if there was a button. I'm not sure if this is a simple bug (and I should PR a fix) or a new design direction.
