### ISSUE TITLE
Celery config options not passing through

### ISSUE THREAD

**Issue by jheld** [mher/flower#906]
Via the docs:  https://flower.readthedocs.io/en/stable/config.html#options

```Standard Celery configuration settings can be overridden in the configuration file. See Celery Configuration reference for a complete listing of all the available settings, and their default values.```

But, I cannot pass `task_routes` because the options parser only looks for flower options, despite saying `celery`-based options will be passed through.

I'm trying to do this on my end (I've already forked the repo), but not sure if I'll end up doing it right.

This seems like a bug to me. Can someone help? @mher maybe? I'm willing to update code paths, just not sure I'm going to attack it in a good way.

The reason I'm looking to do this is that we are planning to separate our flower deployment such that it doesn't read the same settings configuration as the workers, but we'd still like some of the settings (`task_routes` being one) to be passed through.

**Comment by jheld** [comment]
Looks like this isn't a real issue. Not sure why it wasn't working at first, but now it's fine, so I'm closing.

**Comment by jsalandanan** [comment]
Hey there, @jheld, I am actually running into what I believe to be an identical issue to what you reported here. Could I ask if you could expound upon anything you did or observed to fix the issue?

To dive into the specifics a little bit, I'm running with the 0.9.4 version of Flower and 4.2.1 Celery, also trying to pass Celery configuration settings through the flower configuration file. Rather than `task_routes`, I'm trying to pass `broker_use_ssl`, though I imagine the resolution would be somewhat similar.

I'm actually trying to take advantage of #938, but finding that hitting the relevant bits in views is showing that the `broker_use_ssl` setting is still set to None, which causes things like the broker view to fail in the web UI.

I was able to confirm that I was passing the flower configuration file correctly as I could change the port flower was initialized on using the same, but any Celery configuration seems not to. I tried setting a few more common settings in the configuration file as well, such as the `broker_url` and `worker_prefetch_multiplier`, but they also seem not to stick.

Apologies if this is a bit unclear as this is somewhat uncommon ground for me, but I hope you or any other might be able to offer some insight on where I could be going wrong!

**Comment by jheld** [comment]
Sure.

One issue I was dealing with was related to PyCharm working directories. The run configuration did confuse me a lot.

Via terminal things can still be confusing, but I found that it's more clear to do it that way for specific debugging.

It is probably easier not to include the conf path on the shell, at least to start.

Also the celery settings loader does enjoy its own flow, and that can cause issues with flower trying to do it, too.

Are you able to share the shell command you use?

**Comment by jsalandanan** [comment]
Thank you for the reply! Just some added context, but the Celery / Flower deployment is in the context of use in an Airflow deployment. In case you happen to be unfamiliar, Airflow has a wrapper command for starting flower that I believe supports only a subset of the possible command line options when running using the `flower` command directly. In any case, I've tried to use both commands in starting flower whilst passing in a Flower config file:
`airflow flower -fc=/srv/airlflow/flowerconfiguration.py`
`flower --conf=/srv/airflow/flowerconfiguration.py`

I had the thought that a difference between the Celery settings and Flower settings could be causing some trouble, but the farthest I have gotten with pursuing that effort is adding the directory housing the Flower configuration file to my PATH on the machine.

**Comment by jheld** [comment]
Right. I haven't used Airflow yet.

But agreed, celery & flower may be fighting. I think there was some funny thing where the filepath/namespace gets altered in the loader and so it can be harder to figure it out.

Nothing to suggest concretely yet but I let you know if I do.

**Comment by jsalandanan** [comment]
Got it. For me, just knowing about that as a possibility is very helpful. I'll be fighting against this some more with that in mind. Thank you very much for your help and I hope you are able to recall the filepath/namespace issue!

**Comment by jsalandanan** [comment]
Update on this (and, despite what seems like a fairly niche scope, hope this may help someone in the future) - I ended up tracking down the Celery app name used by Airflow for its CeleryExecutor. Simply specifying that with the -A flag sync'd up my Flower instance with the settings I was expecting, including the `broker_use_ssl` param.

Ultimately, that doesn't solve the thing that I was trying to do and having a problem with here (wrt to attempting to pass Celery config options through the Flower config), but there ended up being an easier route for my specific use case.

Thanks a bunch for engaging in this conversation, @jheld, it was very helpful in me coming to this resolution! If you still happen to come to a rediscovery on the exact filepath/namespace issue you had run into, I would be interested in hearing it.
