### ISSUE TITLE
Getting full task kwargs / args

### ISSUE THREAD

**Issue by matomesc** [mher/flower#972]
I have a task whose input is a large `kwargs` dictionary and I would like to keep the full dictionary in flower. Right now it's truncated with `...`. I tried using `format_task` but `kwargs` is already truncated in the task object passed in.

Any ideas?

**Comment by jheld** [comment]
Hi. There are a couple solutions, but only one officially supported that flower can use without any code changes in flower.

You will have to increase the argsrepr and kwargs repr sizes. result repr is in a different spot but also configurable.

For instance if you're running your worker integrated with django, if you add this to the celery.py file in your project directory (where settings.py lives) and then start your worker, it may work:
 app.amqp.argsrepr_maxsize = pow(2, 16)
 app.amqp.kwargsrepr_maxsize = pow(2, 16)

Note 2^16 is quite large.. I chose that as an experiment at one point because of my PR #821 because of an elasticsearch field size limit issue. That said, you likely won't need (or want!) 2^16 bytes flowing through your broker to get to flower. Just a lot of data. Really depends on how big you think your args/kwargs can ever get: napkin math & finger in the wind should do!

**Comment by matomesc** [comment]
Thanks for your help it's working perfectly.

**Comment by XiaobinZhao** [comment]
i set 
 app.amqp.argsrepr_maxsize = pow(2, 16)
 app.amqp.kwargsrepr_maxsize = pow(2, 16)
and
app.Task.resultrepr_maxsize = 10

but when i run a chain task, for example 
```
TASK_CLIENT = Celery(backend="redis://:abc@127.0.0.1:6379/3",
                     broker="amqp://abc:abc@127.0.0.1:5672",
                     strict_typing=True)
task_si = partial(task_signature, app=TASK_CLIENT, immutable=True)
tasks = []
tasks.append(task_si(task1, args=("a big dict")))
tasks.append(task_si(task2, args=("a big dict")))
tasks.append(task_si(task3, args=("a big dict")))

last_task_id = str(uuid1())

chain(tasks, task_id=last_task_id).apply_async()
```
i found， only the args/kwargs of last task: task3 is effective, but the task1/task2 did not? why? how to do it ?
