### ISSUE TITLE
Endpoint /api/tasks returns tasks without their workers

### ISSUE THREAD

**Issue by lukasmatta** [mher/flower#990]
Hello,
I was trying to use `/api/tasks` endpoint in my application and I found out that this endpoint does not return information about tasks' workers. Would it be possible to extend `/api/tasks` endpoint's response, so it would contain worker attribute?

Thanks.

**Comment by lswainemoore** [comment]
Looks like this gets removed here: https://github.com/mher/flower/blob/b57b4d311585182d31bfd4c3f121b5b58990a8dc/flower/api/tasks.py#L530

Can anyone suggest why this might be? I'd also like to have access to worker info on the /api/tasks endpoint. It will save me having to iterate over tasks and hit the /api/task/info endpoint one by one.

**Comment by lswainemoore** [comment]
Appears we are not the first to wonder about this! https://github.com/mher/flower/commit/e0f16df4f8e4da7b12621f9690414b18ef783a87#r13952453

Seems like it happened (in 2014) as part of fixing this issue: https://github.com/mher/flower/issues/177, because the `worker` that's on the task object isn't JSON-serializable.

But I can't reconstruct why the `worker` attribute wasn't just replaced with the worker's hostname, like is done in the task/info endpoint, first here: https://github.com/mher/flower/commit/9a47b54ccf00e138f8dcd338f4d624879b5876fa and revised to be safer here: https://github.com/mher/flower/commit/10cef872a7d4a4022dfdb02ff705b434f94103a7.

Something like this 
```
worker = task.pop('worker', None)
if worker and worker.hostname:
  task['worker'] = worker.hostname
result.append((task_id, task))
```
works for me locally.

@mher would you accept a pull request fixing this? Happy to do so if so.

**Comment by mher** [comment]
@lswainemoore yes, I will
